# Generated by Django 2.1.1 on 2018-10-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='docmsg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='imgmsg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
