# Generated by Django 2.1.3 on 2018-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('did', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=200)),
            ],
        ),
    ]
