# Generated by Django 2.1.1 on 2018-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('uid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
