# Generated by Django 2.1.3 on 2018-11-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('uid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('dp', models.CharField(default='uploads/A@DOCA@IIIT@DPdefualt.png', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userApplied',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('uid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userF',
            fields=[
                ('uid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
