# Generated by Django 2.1.1 on 2018-10-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userApplied',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('uid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
