# Generated by Django 2.1.1 on 2018-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login2', '0002_userapplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='userF',
            fields=[
                ('uid', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
