# Generated by Django 2.1.1 on 2018-10-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login2', '0003_userf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(),
        ),
    ]
