# Generated by Django 2.1.1 on 2018-10-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login2', '0004_auto_20181011_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='dob',
        ),
    ]
