# Generated by Django 2.1.1 on 2018-10-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login2', '0006_auto_20181011_0701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='userApplied',
        ),
    ]
