# Generated by Django 2.1.3 on 2018-11-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginDoctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symtoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symtm1', models.CharField(max_length=50)),
                ('symtm2', models.CharField(max_length=50)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginDoctor.spec')),
            ],
        ),
    ]
