# Generated by Django 2.1.1 on 2018-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('did', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=1000)),
                ('disease', models.CharField(max_length=100)),
            ],
        ),
    ]
