# Generated by Django 2.1.1 on 2018-11-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_record',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginDoctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient_record',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login2.user'),
        ),
    ]
